#include <iostream>
using namespace std;


string Categoria;
string Habilidades;
string Haboculta;
string Peso;
string Altura
string palabra = "palabra";
string palabra = "palabra";


int main()
{

    cout << "Un numero entero es" <<endl<<entero;
    cout << "Un string es" <<endl<<palabra;
    cout << "Un decimal" <<endl<<decimal;
    cout << "Un  booleano es" <<endl<<verdad;
    
    
    return 0;
}
