#include <iostream>
using namespace std;

int main()
{
    for( int i=0; i<18; i++)
    {
        int = i       
    }
    1 == "Categoria";
    2 == "Habilidades";
    3 == "Haboculta";
    4 == "Peso";
    5 == "Altura";
    6 == "GrupoDeHuevo";
    7 == "Sexo";
    8 == "Habitat";
    9 == "Color";
    10 == "Generación";
    11 == "Velocidad";
    12 == "Fortaleza";
    13 == "Precisión";
    14 == "Resistencia";
    15 == "salto";
    16 == "Total";
    17 == "Media";
    /********************************************************
    1 = string Categoria;
    2 = string Habilidades;
    3 = string Haboculta;
    4 = string Peso;
    5 = string Altura;
    6 = string GrupoDeHuevo;
    7 = string Sexo;
    8 = string Habitat;
    9 = string Color;
    10 = string Generación;
    11 = string Velocidad;
    12 = string Fortaleza;
    13 = string Precisión;
    14 = string Resistencia;
    15 = string salto;
    16 = string Total;
    17 = string Media
    cout << "Escribe la categoria del pokemon";
    cin >> Categoria;
    cout << "Escribe las habilidades del pokemon";
    cin >> Habilidades;
    cout << "Escribe la habilidad oculta del pokemon";
    cin >> Haboculta;
    cout << "Escribe el peso del pokemon";
    cin >> Peso;
    cout << "Escribe la Altura del pokemon";
    cin >> Altura;
    cout << "Escribe el grupo de huevo del pokemon";
    cin >> GrupoDeHuevo;
    cout << "Escribe el sexo del pokemon";
    cin >> Sexo;
    cout << "Escribe el Habitat del pokemon";
    cin >> Habitat;//
    ***************************************************/
    for(int i = 0; i <= 17 final; i = i +++)
    {
    i = numero
    printf("Escribe la/el"<<numero<<"del pokemon"<<endl);
    cin << numero;
    }
    
    return 0;
}